name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: set up xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
        
    - name: build ipa
      run: |
        xcodebuild -project mizan.xcodeproj -scheme mizan -sdk iphoneos -configuration Release archive -archivePath $PWD/build/mizan.xcarchive CODE_SIGNING_ALLOWED=NO
        mkdir -p $PWD/build/Payload
        cp -r $PWD/build/mizan.xcarchive/Products/Applications/mizan.app $PWD/build/Payload/
        cd $PWD/build
        zip -r mizan.ipa Payload
        
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mizan.ipa
        path: build/mizan.ipa
